[features]
seeds = false
skip-lint = false
[programs.localnet]
waffle = "86oWnMivppjGV2CDiESKjfTSuNra1kRgPY82QxNgjZJs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/emre/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
